AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'coverage/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - '**/*.haml'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 10

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/For:
  Enabled: false
